query FindUserLostItems($where: UserWhereAuthIdInput!) {
  findUser(where: $where) {
    lostAndFoundState
    ownedLostItems {
      deliveredAt
      description
      id
      imageUrls
      ownedAt
      owner {
        ...UserPublicMeta
      }
      reportedAt
      reporter {
        ...UserPublicMeta
      }
      retrievedAt
      title
      drawer {
        id
        locker {
          lat
          lng
          location
        }
      }
    }
    reportedLostItems {
      deliveredAt
      description
      id
      imageUrls
      ownedAt
      owner {
        ...UserPublicMeta
      }
      reportedAt
      reporter {
        ...UserPublicMeta
      }
      retrievedAt
      title
      drawer {
        id
        locker {
          lat
          lng
          location
        }
      }
    }
  }
}
