query FindSimilarLostItem($lostAt: DateTime!, $userDescription: String!) {
  findSimilarLostItem(lostAt: $lostAt, userDescription: $userDescription) {
    deliveredAt
    description
    descriptionI18n
    id
    imageUrls
    ownedAt
    reportedAt
    reporter {
      ...UserPublicMeta
    }
    retrievedAt
    title
    titleI18n
    approveRate
    rejectRate
    drawer {
      id
      locker {
        lat
        lng
        location
        locationI18n
      }
    }
  }
}
